// examples/react/src/components/Toolbar.tsx
import { useRef, useEffect, useState } from 'react';
import { PolygonBackground } from 'polygon-background';

export function Toolbar() {
  const containerRef = useRef<HTMLDivElement>(null);
  const bgRef = useRef<PolygonBackground | null>(null);
  const [menuOpen, setMenuOpen] = useState(false);

  useEffect(() => {
    if (!containerRef.current || bgRef.current) return;

    bgRef.current = new PolygonBackground(containerRef.current, {
      theme: 'ocean',
      pointCount: 25,
      speed: 0.2,
    });

    return () => {
      bgRef.current?.destroy();
      bgRef.current = null;
    };
  }, []);

  const menuItems = ['Dashboard', 'Settings', 'Profile', 'Logout'];

  return (
    <div ref={containerRef} className="toolbar">
      <div className="toolbar-content">
        <div className="toolbar-left">
          <button className="hamburger" onClick={() => setMenuOpen(!menuOpen)}>
            <span></span>
            <span></span>
            <span></span>
          </button>
          <h4>My Application</h4>
        </div>
        <div className="toolbar-right">
          <button className="icon-btn">🔔</button>
          <button className="icon-btn">👤</button>
        </div>
      </div>
      {menuOpen && (
        <div className="menu">
          {menuItems.map((item) => (
            <button key={item} className="menu-item">{item}</button>
          ))}
        </div>
      )}
    </div>
  );
}

// examples/vue/src/components/Toolbar.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue';
import { PolygonBackground } from 'polygon-background';

const containerRef = ref<HTMLDivElement>();
let bg: PolygonBackground | null = null;
const menuOpen = ref(false);
const menuItems = ['Dashboard', 'Settings', 'Profile', 'Logout'];

onMounted(() => {
  if (containerRef.value) {
    bg = new PolygonBackground(containerRef.value, {
      theme: 'ocean',
      pointCount: 25,
      speed: 0.2,
    });
  }
});

onUnmounted(() => {
  bg?.destroy();
});
</script>

<template>
  <div ref="containerRef" class="toolbar">
    <div class="toolbar-content">
      <div class="toolbar-left">
        <button class="hamburger" @click="menuOpen = !menuOpen">
          <span></span>
          <span></span>
          <span></span>
        </button>
        <h4>My Application</h4>
      </div>
      <div class="toolbar-right">
        <button class="icon-btn">🔔</button>
        <button class="icon-btn">👤</button>
      </div>
    </div>
    <div v-if="menuOpen" class="menu">
      <button v-for="item in menuItems" :key="item" class="menu-item">
        {{ item }}
      </button>
    </div>
  </div>
</template>

<style scoped>
.toolbar {
  position: relative;
  border-radius: 0.5rem;
  overflow: hidden;
  width: 100%;
  max-width: 600px;
  min-height: 60px;
}

.toolbar-content {
  position: relative;
  z-index: 1;
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 1rem 1.5rem;
}

.toolbar-left {
  display: flex;
  align-items: center;
  gap: 1rem;
}

.toolbar-left h4 {
  color: #fff;
  font-size: 1.25rem;
  font-weight: 600;
  margin: 0;
}

.hamburger {
  background: transparent;
  border: none;
  cursor: pointer;
  padding: 0.5rem;
  display: flex;
  flex-direction: column;
  gap: 4px;
}

.hamburger span {
  display: block;
  width: 20px;
  height: 2px;
  background: #fff;
}

.toolbar-right {
  display: flex;
  align-items: center;
  gap: 0.5rem;
}

.icon-btn {
  background: rgba(255, 255, 255, 0.1);
  border: none;
  border-radius: 50%;
  width: 36px;
  height: 36px;
  color: #fff;
  cursor: pointer;
  font-size: 1rem;
}

.menu {
  position: relative;
  z-index: 1;
  border-top: 1px solid rgba(255, 255, 255, 0.1);
  padding: 0.5rem;
}

.menu-item {
  display: block;
  width: 100%;
  text-align: left;
  padding: 0.75rem 1rem;
  background: transparent;
  border: none;
  color: #fff;
  cursor: pointer;
  border-radius: 0.25rem;
}

.menu-item:hover {
  background: rgba(255, 255, 255, 0.1);
}
</style>
